FROM centos:6
RUN yum update -y && yum install -y python-argparse python-setuptools && yum clean all
RUN easy_install pip
RUN pip install -U setuptools
ADD ./ /code/
WORKDIR /code/
CMD python setup.py test
